// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcbMnTGuYS_s_CezMahduFquFfNZOt4M',
    appId: '1:999232013403:web:c1e77e3b64835d67a6ab7e',
    messagingSenderId: '999232013403',
    projectId: 'pimpalgaonthote-15036',
    authDomain: 'pimpalgaonthote-15036.firebaseapp.com',
    storageBucket: 'pimpalgaonthote-15036.firebasestorage.app',
    measurementId: 'G-GK7QQTCF9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldz3vn3ZQbnB8rGAjoub5eO09AreGI2M',
    appId: '1:999232013403:android:bc90d5a1dfa5fd6ca6ab7e',
    messagingSenderId: '999232013403',
    projectId: 'pimpalgaonthote-15036',
    storageBucket: 'pimpalgaonthote-15036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWobcM_3squM68emq5RtmfFiP5VcTrtjU',
    appId: '1:999232013403:ios:0509c47dc9d2a19ba6ab7e',
    messagingSenderId: '999232013403',
    projectId: 'pimpalgaonthote-15036',
    storageBucket: 'pimpalgaonthote-15036.firebasestorage.app',
    iosBundleId: 'com.example.pimpalgaonthote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWobcM_3squM68emq5RtmfFiP5VcTrtjU',
    appId: '1:999232013403:ios:0509c47dc9d2a19ba6ab7e',
    messagingSenderId: '999232013403',
    projectId: 'pimpalgaonthote-15036',
    storageBucket: 'pimpalgaonthote-15036.firebasestorage.app',
    iosBundleId: 'com.example.pimpalgaonthote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqcbMnTGuYS_s_CezMahduFquFfNZOt4M',
    appId: '1:999232013403:web:46aedcd44c54f711a6ab7e',
    messagingSenderId: '999232013403',
    projectId: 'pimpalgaonthote-15036',
    authDomain: 'pimpalgaonthote-15036.firebaseapp.com',
    storageBucket: 'pimpalgaonthote-15036.firebasestorage.app',
    measurementId: 'G-CCXZLSZRH5',
  );
}
